# Generated by Django 4.2.6 on 2023-10-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsurls',
            name='nick',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='lsurls',
            name='short',
            field=models.CharField(max_length=40),
        ),
    ]
